[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true
omit = [
    "nox/_typing.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if _typing.TYPE_CHECKING:",
    "@overload",
]

[tool.mypy]
files = ["nox"]
python_version = "3.7"
show_error_codes = true
strict = true
warn_unreachable = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[[tool.mypy.overrides]]
module = [ "argcomplete", "colorlog.*", "py", "tox.*" ]
ignore_missing_imports = true

[tool.check-manifest]
ignore = [
    "docs/**",
    "noxfile.py",
    "requirements-conda-test.txt",
    "requirements-dev.txt",
    "requirements-test.txt",
    "*.md",
    ".*",
]
